# Generated by Django 3.2.16 on 2023-01-17 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('author', models.CharField(max_length=30, verbose_name='著者')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル画像')),
                ('amazon_url', models.URLField(blank=True, null=True, verbose_name='Amzazonリンク')),
                ('rakuten_url', models.URLField(blank=True, null=True, verbose_name='Rakutenリンク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='追加日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
