# Generated by Django 3.2.16 on 2023-01-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20230119_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
    ]
