# Generated by Django 3.2.16 on 2023-01-20 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_remove_books_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='BookTags',
            new_name='BookTag',
        ),
        migrations.RenameModel(
            old_name='FavoriteBooks',
            new_name='FavoriteBook',
        ),
        migrations.RenameModel(
            old_name='FavoriteTags',
            new_name='FavoriteTag',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='booktag',
            options={'verbose_name': 'BookTag'},
        ),
        migrations.AlterModelOptions(
            name='favoritebook',
            options={'verbose_name': 'FavoriteBook'},
        ),
        migrations.AlterModelOptions(
            name='favoritetag',
            options={'verbose_name': 'FavoriteTag'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'Tag'},
        ),
    ]
