# Generated by Django 3.2.16 on 2023-01-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20230120_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktag',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Booktags', to='books.book', verbose_name='書籍ID'),
        ),
    ]
