# Generated by Django 3.2.16 on 2023-01-26 22:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_alter_booktag_book_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteTag',
            new_name='TagLike',
        ),
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': 'Bookshelf'},
        ),
        migrations.AlterModelOptions(
            name='taglike',
            options={'verbose_name': 'TagLike'},
        ),
    ]
