# Generated by Django 3.2.16 on 2023-01-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20230127_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktag',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='書籍ID'),
        ),
    ]
