# Generated by Django 3.2.16 on 2023-01-31 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_alter_booktag_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booktags', to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='taglike',
            name='booktag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.booktag', verbose_name='書籍タグ'),
        ),
        migrations.AlterField(
            model_name='taglike',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
