# Generated by Django 3.2.16 on 2023-02-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20230201_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='status',
            field=models.CharField(max_length=10, verbose_name='ステータス'),
        ),
    ]
