# Generated by Django 3.2.16 on 2023-02-15 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0011_alter_bookshelf_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booktags', to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='booktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='taglike',
            name='booktag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booktag', verbose_name='書籍タグ'),
        ),
        migrations.AlterField(
            model_name='taglike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
