# Generated by Django 3.2.16 on 2023-12-19 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0016_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bookshelf', to='books.book', verbose_name='書籍'),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookshelf', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategory', to='books.category', verbose_name='カテゴリ'),
        ),
    ]
