# Generated by Django 3.2.16 on 2024-01-10 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='お問い合わせ内容'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(max_length=30, verbose_name='タイトル'),
        ),
    ]
