# Generated by Django 3.2.16 on 2024-01-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_close',
            field=models.BooleanField(default=True, verbose_name='クローズ状態かどうか'),
            preserve_default=False,
        ),
    ]
