# Generated by Django 3.2.16 on 2024-01-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_topic_is_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_close',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='オープン（画面表示）する場合チェックをいれる'),
            preserve_default=False,
        ),
    ]
