# Generated by Django 3.2.16 on 2024-01-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20240115_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=40, verbose_name='タイトル'),
        ),
    ]
