# Generated by Django 3.2.16 on 2024-01-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_alter_topic_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='resistered_date',
            field=models.CharField(default=202307, max_length=6, verbose_name='登録月'),
            preserve_default=False,
        ),
    ]
