# Generated by Django 3.2.16 on 2024-01-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0025_book_resistered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='resistered_date',
            new_name='registered_date',
        ),
    ]
