# Generated by Django 3.2.16 on 2023-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル画像'),
        ),
    ]
