name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: more_books
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate --settings more_books.settings_dev
    - name: Run Tests
      run: |
        python manage.py test --settings more_books.settings_dev
      env:
        DB_HOST: 127.0.0.1
        DB_PASSWORD: postgres
        DB_USER: postgres
    - name: Lint with flake8
      run: |
        flake8 . --max-complexity=10 --max-line-length=90
    # - name: Deployment
    #  run: |
    #    echo "$SECRET_KEY" > secret_key
    #    chmod 600 secret_key
    #    ssh -oStrictHostKeyChecking=no ${SERVER_USER}@${SERVER_HOST} -i secret_key "
    #    cd venv_more_books/more_books &&
    #    git pull &&
    #    source ../bin/activete &&
    #    pkill gunicorn &&
    #    gunicorn --bind 127.0.0.1:8000 more_books.wsgi -D &&
    #    "
    #  env:
    #    SECRET_KEY: ${{ secrets.SECRET_KEY }}
    #    SERVER_USER: ${{ secrets.SERVER_USER }}
    #    SERVER_HOST: ${{ secrets.SERVER_HOST }}
